In [ ]:
import numpy as np


In [ ]:
brigadas=np.array([[["Jose","Antonio","Ricardo"],["Alonso","Jorge","Salvador"]],[["David","Julian","Ricardo"],["Arturo","Ramiro","Esteban"]],[["Arturo","Ricardo","Lucio"],["Jorge","Marco","Juan"]],[["Alonso","Julian","Salvaor"],["Ricardo","Jorge","Esteban"]],[["Lucio","Ramiro","Joaquin"],["Ricardo","Marco","Juan"]]])

In [ ]:
brigadas.ndim

3

In [ ]:
brigadas.shape

(5, 2, 3)

In [ ]:
brigadas[1:3,:,:]

array([[['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']]], dtype='<U8')

In [ ]:
brigadas[1:3,1,:]

array([['Arturo', 'Ramiro', 'Esteban'],
       ['Jorge', 'Marco', 'Juan']], dtype='<U8')

In [ ]:
brigadas[:,1,0:2]

array([['Alonso', 'Jorge'],
       ['Arturo', 'Ramiro'],
       ['Jorge', 'Marco'],
       ['Ricardo', 'Jorge'],
       ['Ricardo', 'Marco']], dtype='<U8')

In [ ]:
sustitutos=np.array([["John","Ringo","Paul"],["Keith","Mick","Charlie"]])

In [ ]:
sustitutos.shape

(2, 3)

In [ ]:
brigadas[4]=sustitutos

In [ ]:
print(brigadas)

[[['Jose' 'Antonio' 'Ricardo']
  ['Alonso' 'Jorge' 'Salvador']]

 [['David' 'Julian' 'Ricardo']
  ['Arturo' 'Ramiro' 'Esteban']]

 [['Arturo' 'Ricardo' 'Lucio']
  ['Jorge' 'Marco' 'Juan']]

 [['Alonso' 'Julian' 'Salvaor']
  ['Ricardo' 'Jorge' 'Esteban']]

 [['John' 'Ringo' 'Paul']
  ['Keith' 'Mick' 'Charlie']]]


In [ ]:
brigadas[1,1,:]=["Parcifal","Gawain","Lancelot"]

In [ ]:
brigadas

array([[['Jose', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Parcifal', 'Gawain', 'Lancelot']],

       [['Salomon', 'Sanson', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvaor'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['John', 'Ringo', 'Paul'],
        ['Keith', 'Mick', 'Charlie']]], dtype='<U8')

In [ ]:
brigadas[2,0,0:2]=["Salomon","Sanson"]

In [ ]:
matriz_1=np.array([[1,2,3],[4,0,-5],[-6,-7,-8]])

In [ ]:
matriz_1.shape

(3, 3)

In [ ]:
matriz_1+100

array([[101, 102, 103],
       [104, 100,  95],
       [ 94,  93,  92]])

In [ ]:
matriz_1[2,:]*3

array([-18, -21, -24])

In [ ]:
3/matriz_1

/tmp/ipykernel_34056/2653568178.py:1: RuntimeWarning: divide by zero encountered in divide
  3/matriz_1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [ ]:
matriz_1/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  0. , -2.5],
       [-3. , -3.5, -4. ]])

In [ ]:
matriz_1>1

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [ ]:
matriz_2=np.array([1,2,3])

In [ ]:
matriz_2.shape

(3,)

In [ ]:
matriz_1*matriz_2

array([[  1,   4,   9],
       [  4,   0, -15],
       [ -6, -14, -24]])

In [ ]:
matriz_3=np.array([[2],[4],[6]])

In [ ]:
matriz_3.shape

(3, 1)

In [ ]:
matriz_3*matriz_1

array([[  2,   4,   6],
       [ 16,   0, -20],
       [-36, -42, -48]])

Metodo

In [ ]:
arreglo_2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arreglo_2.shape

(3, 4)

In [ ]:
arreglo_2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arreglo_2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arreglo_3=np.array([[3,2,1],[4,5,6]])

In [ ]:
arreglo_3.resize(3,3,2)

In [ ]:
arreglo_3

array([[[3, 2],
        [1, 4],
        [5, 6]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
matriz_1.transpose

<function ndarray.transpose>

In [ ]:
matriz_1

array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]])

In [ ]:
origen=np.arange(9).reshape(3,3,1)

In [ ]:
origen

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [ ]:
np.squeeze(origen,2)#Quita dimensiones

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate(arreglo_3,arreglo_2,1)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
ar1=np.array([[1,2],[3,4]])

In [ ]:
ar2=np.array([[5,6],[7,8]])

In [ ]:
np.concatenate((ar1,ar2),1)#eje 1 columnas y eje 0 filas

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Si compraten el mismo nuemro de filas se pega por columnas (1 )y si compaten columnas por filas (0)

In [ ]:
arregl1=np.arange(7,13).reshape(3,2)


In [ ]:
arregl1

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arregloori=np.arange(9).reshape(3,3)

In [ ]:
arregloori

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.append(arregl1,arregloori,axis=1)

array([[ 7,  8,  0,  1,  2],
       [ 9, 10,  3,  4,  5],
       [11, 12,  6,  7,  8]])