In [14]:
import time
lista=list(range(10000000))
inicio=time.time()
[valor * 2 for valor in lista]
print("Tiempo de ejcucion con listas: ", time.time()-inicio)

Tiempo de ejcucion con listas:  1.0058579444885254


In [18]:
import numpy as np
arreglo=np.arange(10000000)
inicio=time.time()
arreglo*2
print("Tiempo de ejecucion con numpy: ", time.time()-inicio)

Tiempo de ejecucion con numpy:  0.02850174903869629


In [19]:
!pip install numpy

In [20]:
import numpy as np

In [67]:
arreglo=np.array([1,2,3,4,5], dtype=float)
print(arreglo)

[1. 2. 3. 4. 5.]


In [68]:
print("El numero de dimendiones de el arreglo es:", arreglo.ndim)
print("La forma del arreglo es :", arreglo.shape)
print("El total de elementos en el arreglo es: ",arreglo.size)
print("Lostipos de daros en el arreglo son: ", arreglo.dtype)

El numero de dimendiones de el arreglo es: 1
La forma del arreglo es : (5,)
El total de elementos en el arreglo es:  5
Lostipos de daros en el arreglo son:  float64


In [35]:
arreglo_2d=np.array([[1,2,3],[4,5,6]],dtype=float)

In [36]:
print("El numero de dimendiones de el arreglo es:", arreglo_2d.ndim)
print("La forma del arreglo es :", arreglo_2d.shape)
print("El total de elementos en el arreglo es: ",arreglo_2d.size)
print("Lostipos de daros en el arreglo son: ", arreglo_2d.dtype)

El numero de dimendiones de el arreglo es: 2
La forma del arreglo es : (2, 3)
El total de elementos en el arreglo es:  6
Lostipos de daros en el arreglo son:  float64


In [45]:
arreglo_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arreglo_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
print("El numero de dimendiones de el arreglo es:", arreglo_3d.ndim)
print("La forma del arreglo es :", arreglo_3d.shape)
print("El total de elementos en el arreglo es: ",arreglo_3d.size)
print("Lostipos de daros en el arreglo son: ", arreglo_3d.dtype)

El numero de dimendiones de el arreglo es: 3
La forma del arreglo es : (2, 2, 3)
El total de elementos en el arreglo es:  12
Lostipos de daros en el arreglo son:  int64


In [47]:
ceros=np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
unos=np.ones((2,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
vacio=np.empty((3,4))
vacio

array([[1.82030665e-315, 0.00000000e+000, 2.10077583e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.35541533e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.46151512e-312,
        2.41907520e-312]])

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [54]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [62]:
np.random.rand(2,3)

array([[0.65180186, 0.02763197, 0.98783704],
       [0.3020353 , 0.03499789, 0.29782845]])

In [65]:
arreglo1=np.array([[1,0],[-1,1]])
arreglo

array([[ 1,  0],
       [-1,  1]])

In [66]:
arreglo1/0

/tmp/ipykernel_14912/1689033109.py:1: RuntimeWarning: divide by zero encountered in divide
  arreglo1/0
/tmp/ipykernel_14912/1689033109.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo1/0


array([[ inf,  nan],
       [-inf,  inf]])

In [70]:
arreglo2=np.array([[np.inf,np.nan],[1,2]])
arreglo2

array([[inf, nan],
       [ 1.,  2.]])

In [72]:
array_inf=np.array([1,2.5])**5233
print(array_inf)

[ 1. inf]


/tmp/ipykernel_14912/2252220341.py:1: RuntimeWarning: overflow encountered in power
  array_inf=np.array([1,2.5])**5233
